name: Supply Chain
on: [ push, workflow_dispatch ]

jobs:
   bridgecrew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run Prisma Cloud 
        id: prisma-cloud
        uses: bridgecrewio/checkov-action@master
        env:
          PRISMA_API_URL: https://api.jp.prismacloud.io
        with:
          api-key: ${{ secrets.BC_API_KEY }}
